#!/usr/bin/env rake

require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rake/packagetask'
require 'rubygems/package_task'

spec = eval(File.read('phoenix_auth.gemspec'))

Gem::PackageTask.new(spec) do |p|
  p.gem_spec = spec
end