#!/usr/bin/env rake

require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rake/packagetask'
require 'rubygems/package_task'
require 'phoenix/core/testing_support/common_rake'

RSpec::Core::RakeTask.new

spec = eval(File.read('phoenix_core.gemspec'))

task :routes => 'app:environment' do
  Rails.application.reload_routes!
  all_routes = Phoenix::Core::Engine.routes.routes
end

Gem::PackageTask.new(spec) do |p|
  p.gem_spec = spec
end

desc "Generates a dummy app for testing"
task :test_app do
  ENV['LIB_NAME'] = 'phoenix_core'
  Rake::Task['common:test_app'].invoke
end